name: test

on:
  pull_request:
    types: [labeled]

jobs:
  authorize:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.1.0
        with:
          route: GET /repos/:repository/collaborators/${{ github.actor }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  acceptance-tests:
    if: ${{ github.event.label.name == 'run-testacc' }}
    needs: [authorize]
    runs-on: ubuntu-latest
    steps:
      - run: test ${{ secrets.FOO }} = bar
      - run: ls
